# Chronic Asthma Therapy - Ars Therapeutica
# Generated by Lando(ChemBio(Operator)

from Ars_Therapeutica.ars_therapeutica.types import (
    Imscription, D, T, R, P, F, K, G, Gamma, Phi, H, S, W,
    distance, delta_primitives, tier, c_score, meet, join
)

HEALTHY_AIRWAY = Imscription(
    D=D.TRIANGLE, T=T.NET, R=R.LR, P=P.PMS, F=F.ETH, K=K.MOD,
    G=G.BETH, Gamma=Gamma.SEQ, Phi=Phi.C, H=H.N0, S=S.N_M, W=W.TRIV)

CHRONIC_ASTHMA = Imscription(
    D=D.TRIANGLE, T=T.BOWTIE, R=R.LR, P=P.ASYM, F=F.ELL, K=K.MOD,
    G=G.GIMEL, Gamma=Gamma.OR, Phi=Phi.SUPER, H=H.N1, S=S.N_M, W=W.Z2)

EPIGENETIC_RESET = Imscription(
    D=D.TRIANGLE, T=T.NET, R=R.LR, P=P.PMS, F=F.ETH, K=K.SLOW,
    G=G.BETH, Gamma=Gamma.SEQ, Phi=Phi.C, H=H.N0, S=S.N_N, W=W.TRIV)

TSLP_INHIBITOR = Imscription(
    D=D.TRIANGLE, T=T.NET, R=R.SUPER, P=P.ASYM, F=F.ETH, K=K.MOD,
    G=G.BETH, Gamma=Gamma.AND, Phi=Phi.C, H=H.N0, S=S.ONE_ONE, W=W.TRIV)

BARRIER_RESTORATIVE = Imscription(
    D=D.TRIANGLE, T=T.NET, R=R.LR, P=P.PMS, F=F.ETH, K=K.MOD,
    G=G.BETH, Gamma=Gamma.SEQ, Phi=Phi.SUB, H=H.N0, S=S.ONE_ONE, W=W.TRIV)

P1 = meet(CHRONIC_ASTHMA, EPIGENETIC_RESET)
P2 = meet(P1, TSLP_INHIBITOR)
P3 = join(P2, BARRIER_RESTORATIVE)

if __name__ == "__main__":
    print(f"Phase1 d(healthy)={distance(P1, HEALTHY_AIRWAY):.4f}")
    print(f"Phase2 d(healthy)={distance(P2, HEALTHY_AIRWAY):.4f}")
    print(f"Phase3 d(healthy)={distance(P3, HEALTHY_AIRWAY):.4f}")
    print(f"Final delta={delta_primitives(P3, HEALTHY_AIRWAY)}")
    print(f"Tier={tier(P3)} C-score={c_score(P3):.4f}")
